Repository openshift/ironic-ipa-downloader, pull requests merged in 2019-07, with the labels that each got.

#1 Add Dockerfile.ocp
  Dockerfile.ocp
Labels: size/XS

#2 Build container from rhel7
  Dockerfile.ocp
Labels: size/XS

#5 Adding OWNERS file
  OWNERS
Labels: size/S

#3 Switch ocp image to use a packaged IPA image
  Dockerfile.ocp
  get-resource.sh
Labels: approved, lgtm, size/S

#7 Merge latest changes from upstream
  Dockerfile
  get-resource.sh
Labels: approved, lgtm, size/XS
