Repository openshift/ironic-ipa-downloader, pull requests merged in 2020-02, with the labels that each got.

#24 Bug 1798385: Use dnf to download the only package we need
  Dockerfile.ocp
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#23 Bug 1798491: Add a way to modify ipa image
  Dockerfile.ocp
  build-ipa.sh
  get-resource.sh
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#28 Bug 1804128: Ramdisk arch should not be hardcoded
  build-ipa.sh
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#27 Bug1798272 : DHCPv6 set hostname and predictable hostname
  build-ipa.sh
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#29 bug 1804278: set hostnames and make DHCPv6 IDs predictable
  Dockerfile.ocp
  build-ipa.sh
  get-resource.sh
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/M
