Repository openshift/ironic-ipa-downloader, pull requests merged in 2020-12, with the labels that each got.

#53 Bug 1899190: Apply hack to eventlet
  chrooted.sh
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#55 Trigger a build
  Dockerfile.ocp
Labels: approved, lgtm

#54 bug 1902797: Always set hostname from DHCP6_FQDN_FQDN if set
  chrooted.sh
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, cherry-pick-approved, lgtm

#52 Bug 1905004: Use new ironic-python-agent images
  Dockerfile.ocp
  build-ipa.sh
  chrooted.sh
  get-resource.sh
  main-packages-list.txt
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, cherry-pick-approved, lgtm
