Repository openshift/ironic-ipa-downloader, pull requests merged in 2021-06, with the labels that each got.

#70 Bug 1963204: Update IPA ramdisk image for RHEL 8.4
  Dockerfile.ocp
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#71 Fix for UEFI bootloader entry
  Dockerfile.ocp
Labels: approved, lgtm

#74 Bug 1972213: Fix for UEFI bootloader entry
  Dockerfile.ocp
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, group-lead-approved, lgtm

#76 Use 4.9 base image
  Dockerfile.ocp
Labels: approved, lgtm

#77 Bug 1975531: [release-4.6] Update ipa version
  Dockerfile.ocp
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm
