Repository openshift/ironic-ipa-downloader, pull requests merged in 2021-04, with the labels that each got.

#64 Upgrade to latest ipa-ramdisk
  Dockerfile.ocp
Labels: approved, lgtm

#66 Update ipa-ramdisk to latest for 4.8
  Dockerfile.ocp
Labels: approved, lgtm

#63 Bug 1937809: Update ironic-images package
  Dockerfile.ocp
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#65 Bug 1948513: Add support for no_proxy
  get-resource.sh
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm
